apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: matheuscaldeira/api-conversao:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /ready
              port: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "32Mi"
            limits:
              cpu: "400m"
              memory: "32Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-conversao
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
